### ISSUE TITLE
Application won’t start

### ISSUE THREAD

**Issue by raysanc86** [artrepreneur/Zulu#15]
I downloaded the DMG file, installed PKTWallet and dragged it over to applications. However, when I click on the application to start, it bounces in the dock for a few seconds and then just disappears.

**Comment by artrepreneur** [comment]
> I downloaded the DMG file, installed PKTWallet and dragged it over to applications. However, when I click on the application to start, it bounces in the dock for a few seconds and then just disappears.

What environment, version of MacOS?

**Comment by vestedcrypto** [comment]
Same issue for me. Running Big Sur 11.2.3 on silicone/m1 mac mini (16gb ram), application bounces in dock then takes no action. Right-clicking "show recents" reports "no available windows"

**Comment by raysanc86** [comment]
> version

**Comment by raysanc86** [comment]
> > I downloaded the DMG file, installed PKTWallet and dragged it over to applications. However, when I click on the application to start, it bounces in the dock for a few seconds and then just disappears.
> 
> What environment, version of MacOS?

Big Sur 11.2.3. Verison 32 and 39 bounce in the doc and do not open.

**Comment by thedillondillondillon** [comment]
Do you know what versions of os11 happen to work with the wallet ZULU version?      It worked well on OS11.2   but now it isn't working on os11.2.3 (bounces on dock and then disapears)... Mac has a way of getting me back to os11.2.1 but not back to os11.2...
Do we know,,,

has  if anyone has gotten wallet version v.1.0.0-beta.39 aka ZULU to work on mac os11.2.1?
